// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// viaroute_osrmc
std::string viaroute_osrmc(double startlat, double startlng, double endlat, double endlng);
RcppExport SEXP osrmrcpp_viaroute_osrmc(SEXP startlatSEXP, SEXP startlngSEXP, SEXP endlatSEXP, SEXP endlngSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type startlat(startlatSEXP);
    Rcpp::traits::input_parameter< double >::type startlng(startlngSEXP);
    Rcpp::traits::input_parameter< double >::type endlat(endlatSEXP);
    Rcpp::traits::input_parameter< double >::type endlng(endlngSEXP);
    __result = Rcpp::wrap(viaroute_osrmc(startlat, startlng, endlat, endlng));
    return __result;
END_RCPP
}
// viaroute_osrmcv
CharacterVector viaroute_osrmcv(NumericVector startlat, NumericVector startlng, NumericVector endlat, NumericVector endlng);
RcppExport SEXP osrmrcpp_viaroute_osrmcv(SEXP startlatSEXP, SEXP startlngSEXP, SEXP endlatSEXP, SEXP endlngSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type startlat(startlatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type startlng(startlngSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type endlat(endlatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type endlng(endlngSEXP);
    __result = Rcpp::wrap(viaroute_osrmcv(startlat, startlng, endlat, endlng));
    return __result;
END_RCPP
}
// viaroute_parallel
std::vector<std::string> viaroute_parallel(NumericVector startlat, NumericVector startlng, NumericVector endlat, NumericVector endlng);
RcppExport SEXP osrmrcpp_viaroute_parallel(SEXP startlatSEXP, SEXP startlngSEXP, SEXP endlatSEXP, SEXP endlngSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type startlat(startlatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type startlng(startlngSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type endlat(endlatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type endlng(endlngSEXP);
    __result = Rcpp::wrap(viaroute_parallel(startlat, startlng, endlat, endlng));
    return __result;
END_RCPP
}
// osrmc_minexample
std::string osrmc_minexample(double startlat, double startlng, double endlat, double endlng);
RcppExport SEXP osrmrcpp_osrmc_minexample(SEXP startlatSEXP, SEXP startlngSEXP, SEXP endlatSEXP, SEXP endlngSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type startlat(startlatSEXP);
    Rcpp::traits::input_parameter< double >::type startlng(startlngSEXP);
    Rcpp::traits::input_parameter< double >::type endlat(endlatSEXP);
    Rcpp::traits::input_parameter< double >::type endlng(endlngSEXP);
    __result = Rcpp::wrap(osrmc_minexample(startlat, startlng, endlat, endlng));
    return __result;
END_RCPP
}
