# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

viaroute_osrmc <- function(startlat, startlng, endlat, endlng) {
    .Call('osrmrcpp_viaroute_osrmc', PACKAGE = 'osrmrcpp', startlat, startlng, endlat, endlng)
}

viaroute_osrmcv <- function(startlat, startlng, endlat, endlng) {
    .Call('osrmrcpp_viaroute_osrmcv', PACKAGE = 'osrmrcpp', startlat, startlng, endlat, endlng)
}

viaroute_parallel <- function(startlat, startlng, endlat, endlng) {
    .Call('osrmrcpp_viaroute_parallel', PACKAGE = 'osrmrcpp', startlat, startlng, endlat, endlng)
}

osrmc_minexample <- function(startlat, startlng, endlat, endlng) {
    .Call('osrmrcpp_osrmc_minexample', PACKAGE = 'osrmrcpp', startlat, startlng, endlat, endlng)
}

